title: Mon Projet OhMyFood
description: Un site web pour mon projet
theme: jekyll-theme-minimal


github:
  is_project_page: true
  repository_url: https://github.com/Emmie1428/OhMyFood


source: .
destination: ./_site

sass:
  style: compressed